# parametros.py

HORA_SALIDA = "08:00"

JORNADA_MAX_MIN = 480
JORNADA_SABADO_MIN = 240
HORA_MAX_REGRESO = "17:00"

VELOCIDAD_MEDIA_KMH = 35

TIEMPO_CARGA_DEPOSITO = 20
TIEMPO_DESCARGA_DEFECTO = 15
TIEMPO_PREPARACION_NUEVA_SALIDA_MIN = 60

CAPACIDAD_GRANDE = 5000
CAPACIDAD_MEDIANA = 3000
CAPACIDAD_URBANA = 1800

PERMITIR_ENTREGAS_SABADO = True
PERMITIR_ENTREGAS_DOMINGO = False
PERMITIR_ENTREGAS_EXTRAORDINARIAS = True
PERMITIR_HORAS_EXTRA = False

PORCENTAJE_OCUPACION_OBJETIVO = 0.90

ESTADO_PROGRAMADO = "PROGRAMADO"
ESTADO_EXTRAORDINARIO = "EXTRAORDINARIO"
ESTADO_PENDIENTE_VALIDACION = "PENDIENTE_VALIDACION"

# Costos estimados para demo y Power BI. Ajustar con datos reales de la empresa.
COSTO_FIJO_CAMION = 900
COSTO_POR_KM = 38
COSTO_POR_HORA = 420
COSTO_POR_PARADA = 45

